 language: ruby
  rvm:
  - 2.3.1
  install:
  - bundle install
  before_script:
  - psql -c 'create database template_test;' -U postgres
  services:
  - postgresql

addons:
  code_climate:
    repo_token: af07d16865af867bfefc8ee7f8c0492fc94915f52d1c288cd3bc1df8405145d7
