# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46732743cb5309e539349aac17dfe144f5ac4e1d68a71fcad54852e730c3918c69c59fa61cc7de5a0cf6ea582e0a012e0d6de471cae9338f5976664aaedcc629

test:
  secret_key_base: 6b3640fcccbaf468259edd2f839b3c66a45c8616700fdb116712d16d5077ad125f39ac9ba0ef3b2b4491dae2ac1594ba047e32b49f0d8f81d485514be4ba13e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
